# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Set target Ruby version to 3.4
AllCops:
  TargetRubyVersion: 3.4

# Prefer single quotes over double quotes
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
